bimodal:
  fit_kwds:
    batch_size: 32
    epochs: 1000
  model_kwds:
    output_shape: 20
    clip_to_bernstein_domain: false
    scale_base_distribution: false
    scale_data: true
    shift_data: true
    bernstein_bijector_kwargs:
        extrapolation: true
    bounds: [-3, 3]
    allow_flexible_bounds: true
    smooth_bounds: true
  scale_data_to_domain: false
